function z = KbyR_CUDA_Vcycle(r)
    global meshHierarchy_;
    global weightFactorJacobi_;

    mh1 = meshHierarchy_(1);
    mh2 = meshHierarchy_(2);
    mh3 = meshHierarchy_(3);

    fixedMask1 = mh1.fixedDOFs;
    fixedMask2 = mh2.fixedDOFs;
    fixedMask3 = mh3.fixedDOFs;

    z = sgld_vcycle3_exact_cuda_mex_fixed( ...
        full(double(r(:))), ...
        mh2, ...
        mh3, ...
        full(double(mh1.diagK(:))), ...
        fixedMask1, ...
        full(double(mh2.diagK(:))), ...
        fixedMask2, ...
        fixedMask3, ...
        weightFactorJacobi_, ...
        @Debug_CoarseSolve);
end