%% Test full PCG MEX with embedded CUDA V-cycle preconditioner

global meshHierarchy_;
global weightFactorJacobi_;

mh1 = meshHierarchy_(1);
mh2 = meshHierarchy_(2);
mh3 = meshHierarchy_(3);

fixedMask1 = false(mh1.numDOFs,1);
fixedMask1(mh1.fixedDOFs) = true;

fixedMask2 = false(mh2.numDOFs,1);
fixedMask2(mh2.fixedDOFs) = true;

fixedMask3 = false(mh3.numDOFs,1);
fixedMask3(mh3.fixedDOFs) = true;

fprintf('\nStarting full CUDA PCG MEX with CUDA V-cycle...\n');

tStart = tic;

[U_pcg_vcycle_mex, its_pcg_vcycle_mex, relres_pcg_vcycle_mex] = ...
    sgld_pcg_vcycle_cuda_mex( ...
        full(double(F_(:))), ...
        [], ...
        int32(mh1.nodeToElements), ...
        int32(mh1.eNodMat), ...
        full(double(mh1.eleModulus(:))), ...
        full(double(mh1.Ks)), ...
        mh2, ...
        mh3, ...
        full(double(mh1.diagK(:))), ...
        fixedMask1, ...
        full(double(mh2.diagK(:))), ...
        fixedMask2, ...
        fixedMask3, ...
        weightFactorJacobi_, ...
        tol_, ...
        maxIT_, ...
        'printP_ON', ...
        @Debug_CoarseSolve);

fprintf('Full CUDA PCG V-cycle MEX completed.\n');
fprintf('Iterations: %d\n', its_pcg_vcycle_mex);
fprintf('Final relres: %.12e\n', relres_pcg_vcycle_mex);
fprintf('Full CUDA PCG V-cycle MEX cost: %.3f s\n', toc(tStart));
