
%% Validate MATLAB-matching CUDA V-cycle, then run full PCG MEX

global meshHierarchy_;
global weightFactorJacobi_;

mh1 = meshHierarchy_(1);
mh2 = meshHierarchy_(2);
mh3 = meshHierarchy_(3);

fixedMask1 = logical(mh1.fixedDOFs(:));
fixedMask2 = logical(mh2.fixedDOFs(:));
fixedMask3 = logical(mh3.fixedDOFs(:));

%% A. Standalone V-cycle validation
rng(1);
r = randn(mh1.numDOFs,1);
r(fixedMask1) = 0;

fprintf('\n=== MATLAB-match standalone V-cycle ===\n');

[z_cuda,r2_cuda,r3_cuda] = sgld_vcycle3_matlabmatch_cuda_mex( ...
    full(double(r(:))), ...
    mh2, ...
    mh3, ...
    full(double(mh1.diagK(:))), ...
    fixedMask1, ...
    full(double(mh2.diagK(:))), ...
    fixedMask2, ...
    fixedMask3, ...
    weightFactorJacobi_, ...
    @Debug_CoarseSolve);

r2_ref = Solving_RestrictResidual(r,2);
r3_ref = Solving_RestrictResidual(r2_ref,3);
z_ref  = Solving_Vcycle(r);

fprintf('r2 relErr: %.12e\n', ...
    norm(r2_cuda-r2_ref)/max(norm(r2_ref),1e-30));
fprintf('r3 relErr: %.12e\n', ...
    norm(r3_cuda-r3_ref)/max(norm(r3_ref),1e-30));
fprintf('z absErr:  %.12e\n',norm(z_cuda-z_ref));
fprintf('z relErr:  %.12e\n', ...
    norm(z_cuda-z_ref)/max(norm(z_ref),1e-30));
fprintf('fixed z CUDA norm:  %.12e\n',norm(z_cuda(fixedMask1)));
fprintf('fixed z MATLAB norm: %.12e\n',norm(z_ref(fixedMask1)));
fprintf('r''z CUDA:   %.12e\n',r'*z_cuda);
fprintf('r''z MATLAB: %.12e\n',r'*z_ref);

%% B. Full PCG MEX using the MATLAB-matching V-cycle
fprintf('\n=== Full PCG MEX with MATLAB-match V-cycle ===\n');

tStart = tic;

[U_match,its_match,relres_match] = ...
    sgld_pcg_vcycle_matlabmatch_cuda_mex( ...
        full(double(F_(:))), ...
        [], ...
        int32(mh1.nodeToElements), ...
        int32(mh1.eNodMat), ...
        full(double(mh1.eleModulus(:))), ...
        full(double(mh1.Ks)), ...
        mh2, ...
        mh3, ...
        full(double(mh1.diagK(:))), ...
        fixedMask1, ...
        full(double(mh2.diagK(:))), ...
        fixedMask2, ...
        fixedMask3, ...
        weightFactorJacobi_, ...
        tol_, ...
        maxIT_, ...
        'printP_ON', ...
        @Debug_CoarseSolve);

fprintf('Iterations: %d\n',its_match);
fprintf('Final relres: %.12e\n',relres_match);
fprintf('Total cost: %.3f s\n',toc(tStart));
