%% Test full CUDA PCG with fully GPU-resident sparse coarse solve

global meshHierarchy_;
global weightFactorJacobi_;
global cholFac_;
global cholPermut_;

mh1 = meshHierarchy_(1);
mh2 = meshHierarchy_(2);
mh3 = meshHierarchy_(3);

fixedMask1 = logical(mh1.fixedDOFs(:));
fixedMask2 = logical(mh2.fixedDOFs(:));
fixedMask3 = logical(mh3.fixedDOFs(:));

% cholPermut_ satisfies P*v = v(coarsePerm).
[permRow,permCol] = find(cholPermut_);
coarsePerm = zeros(size(cholPermut_,1),1,'int32');
coarsePerm(permRow) = int32(permCol);

assert(issparse(cholFac_));
assert(size(cholFac_,1) == size(cholFac_,2));
assert(size(cholFac_,1) == nnz(~fixedMask3));
assert(numel(coarsePerm) == size(cholFac_,1));
assert(isequal(sort(double(coarsePerm)),(1:numel(coarsePerm))'));

fprintf('\n=== Fully GPU-resident PCG + V-cycle + coarse Cholesky ===\n');
fprintf('Coarse dimension: %d\n',size(cholFac_,1));
fprintf('Coarse factor nnz: %d\n',nnz(cholFac_));

g = gpuDevice;
fprintf('GPU: %s\n',g.Name);
fprintf('Available memory before MEX: %.3f GB\n',g.AvailableMemory/2^30);

tStart = tic;

[U_gpucoarse,its_gpucoarse,relres_gpucoarse] = ...
    sgld_pcg_vcycle_gpucoarse_cuda_mex( ...
        full(double(F_(:))), ...
        [], ...
        int32(mh1.nodeToElements), ...
        int32(mh1.eNodMat), ...
        full(double(mh1.eleModulus(:))), ...
        full(double(mh1.Ks)), ...
        mh2, ...
        mh3, ...
        full(double(mh1.diagK(:))), ...
        fixedMask1, ...
        full(double(mh2.diagK(:))), ...
        fixedMask2, ...
        fixedMask3, ...
        cholFac_, ...
        coarsePerm, ...
        weightFactorJacobi_, ...
        tol_, ...
        maxIT_, ...
        'printP_ON');

elapsed = toc(tStart);

fprintf('GPU-coarse PCG completed.\n');
fprintf('Iterations: %d\n',its_gpucoarse);
fprintf('Final relres: %.12e\n',relres_gpucoarse);
fprintf('Total cost: %.3f s\n',elapsed);
